const KEY='carteira-clara-v1';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const number=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:4});
let db=load(), selected='all', page='portfolio';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{clients:[]}}catch{return{clients:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function safe(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2700)}
function total(c){return(c.assets||[]).reduce((a,x)=>a+x.quantity*(x.price||x.cost),0)}
function invested(c){return(c.assets||[]).reduce((a,x)=>a+x.quantity*x.cost,0)}
function fmt(v){return money.format(v||0)}
function formatQuoteDate(value){const digits=String(value||'').replace(/\D/g,'');return digits.length===8?`${digits.slice(6,8)}/${digits.slice(4,6)}/${digits.slice(0,4)}`:'data indisponível'}
function dateText(){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
document.querySelector('#today').textContent=dateText();
function render(){
  document.querySelector('#client-strip').innerHTML=`<button class="client-tab all ${selected==='all'?'active':''}" data-client="all">Todos os clientes</button>`+db.clients.map(c=>`<button class="client-tab ${selected===c.id?'active':''}" data-client="${c.id}">${safe(c.name)}</button>`).join('');
  document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>{selected=b.dataset.client;render()});
  renderPortfolio();renderClients();
}
function renderPortfolio(){
 const clients=selected==='all'?db.clients:db.clients.filter(c=>c.id===selected);const assets=clients.flatMap(c=>(c.assets||[]).map(a=>({...a,clientName:c.name,clientId:c.id})));const mv=clients.reduce((n,c)=>n+total(c),0),cost=clients.reduce((n,c)=>n+invested(c),0),pnl=mv-cost, pct=cost?pnl/cost*100:0;
 document.querySelector('#crumb-client').textContent=selected==='all'?'Visão geral':(clients[0]?.name||'Visão geral');
 const content=document.querySelector('#portfolio-content');
 if(!db.clients.length){content.innerHTML=`<div class="empty"><div class="empty-icon">♙</div><h2>Comece pelo primeiro cliente</h2><p>Crie uma carteira separada para cada cliente e acompanhe os investimentos em um só lugar.</p><button class="primary" id="empty-new">＋ Cadastrar primeiro cliente</button></div>`;document.querySelector('#empty-new').onclick=()=>document.querySelector('#client-dialog').showModal();return}
 const head=`<div class="stats"><div class="stat-card"><div class="stat-label">Patrimônio de mercado</div><div class="stat-value">${fmt(mv)}</div><div class="stat-foot">${selected==='all'?`${db.clients.length} clientes`:'Carteira de '+safe(clients[0]?.name)}</div></div><div class="stat-card"><div class="stat-label">Total investido</div><div class="stat-value">${fmt(cost)}</div><div class="stat-foot">Custo médio informado</div></div><div class="stat-card"><div class="stat-label">Resultado acumulado</div><div class="stat-value ${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${fmt(pnl)}</div><div class="stat-foot ${pnl>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2).replace('.',',')}% sobre o custo</div></div><div class="stat-card"><div class="stat-label">Ativos na carteira</div><div class="stat-value">${assets.length}</div><div class="stat-foot">${new Set(assets.map(a=>a.symbol)).size} códigos distintos</div></div></div>`;
 const rows=assets.map(a=>{const gain=a.quantity*((a.price||a.cost)-a.cost),gpct=a.cost?((a.price||a.cost)-a.cost)/a.cost*100:0;return `<tr><td><div class="asset-symbol">${safe(a.symbol)}</div><div class="asset-name">${selected==='all'?safe(a.clientName):safe(a.name||'Ativo')}</div></td><td>${number.format(a.quantity)}</td><td>${fmt(a.cost)}</td><td>${a.price?fmt(a.price):'<span class="stat-foot">Sem cotação</span>'}</td><td>${fmt(a.quantity*(a.price||a.cost))}</td><td class="${gain>=0?'positive':'negative'}">${gain>=0?'+':''}${fmt(gain)}<div class="asset-name ${gain>=0?'positive':'negative'}">${gpct>=0?'+':''}${gpct.toFixed(2).replace('.',',')}%</div></td><td class="position-actions"><button class="subtle-btn edit-asset" data-client="${a.clientId}" data-symbol="${safe(a.symbol)}" title="Editar posição" aria-label="Editar ${safe(a.symbol)}">✎</button><button class="subtle-btn delete-asset" data-client="${a.clientId}" data-symbol="${safe(a.symbol)}" title="Excluir posição" aria-label="Excluir ${safe(a.symbol)}">×</button></td></tr>`}).join('');
 content.innerHTML=head+(assets.length?`<div class="panel"><div class="panel-heading"><div><h2>Posições</h2><p>${selected==='all'?'Consolidado de todos os clientes':'Ativos desta carteira'}</p></div><button class="primary" id="add-asset">＋ Ativo</button></div><div class="table-wrap"><table><thead><tr><th>Ativo / cliente</th><th>Quantidade</th><th>Custo médio</th><th>Cotação</th><th>Valor atual</th><th>Rentabilidade</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div class="note">${db.quoteDate?'Último pregão disponível: '+db.quoteDate.slice(6,8)+'/'+db.quoteDate.slice(4,6)+'/'+db.quoteDate.slice(0,4)+'. ':''}${db.updatedAt?'Preços sincronizados em '+new Date(db.updatedAt).toLocaleString('pt-BR')+'. ':''}A rentabilidade considera apenas variação de preço e custo médio cadastrado.</div></div>`:`<div class="empty"><div class="empty-icon">↗</div><h2>${selected==='all'?'Adicione o primeiro investimento':'Esta carteira ainda está vazia'}</h2><p>Registre quantidade e custo médio. O valor de mercado será calculado com a cotação disponível ou com o custo informado.</p><button class="primary" id="add-asset-empty">＋ Adicionar ativo</button></div>`);
 const add=document.querySelector('#add-asset')||document.querySelector('#add-asset-empty');if(add)add.onclick=()=>openAsset();document.querySelectorAll('.edit-asset').forEach(b=>b.onclick=()=>openAsset(b.dataset.client,b.dataset.symbol));document.querySelectorAll('.delete-asset').forEach(b=>b.onclick=()=>deleteAsset(b.dataset.client,b.dataset.symbol));
}
function deleteAsset(clientId,symbol){const client=db.clients.find(c=>c.id===clientId);const asset=client?.assets.find(a=>a.symbol===symbol);if(!client||!asset)return;if(!window.confirm(`Excluir ${asset.symbol} da carteira de ${client.name}?`))return;client.assets=client.assets.filter(a=>a.symbol!==symbol);save();render();toast(`${asset.symbol} removido da carteira`)}
function renderClients(){const el=document.querySelector('#clients-content');if(!db.clients.length){el.innerHTML='<div class="empty"><div class="empty-icon">♙</div><h2>Nenhum cliente cadastrado</h2><p>Adicione um cliente para criar a primeira carteira.</p><button class="primary" id="client-empty-add">＋ Novo cliente</button></div>';document.querySelector('#client-empty-add').onclick=()=>document.querySelector('#client-dialog').showModal();return}el.innerHTML='<div class="client-list">'+db.clients.map(c=>`<div class="client-row"><div class="client-initial">${safe(c.name[0].toUpperCase())}</div><div class="client-info"><b>${safe(c.name)}</b><small>${safe(c.ref||'Carteira de investimentos')} · ${(c.assets||[]).length} ativos</small></div><div class="client-value">${fmt(total(c))}<small>patrimônio estimado</small></div><button class="secondary open-client" data-id="${c.id}">Abrir carteira</button></div>`).join('')+'</div>';document.querySelectorAll('.open-client').forEach(b=>b.onclick=()=>{selected=b.dataset.id;showPage('portfolio')})}
function showPage(p){page=p;document.querySelector('#portfolio-page').classList.toggle('hidden',p!=='portfolio');document.querySelector('#clients-page').classList.toggle('hidden',p!=='clients');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function newClient(){document.querySelector('#client-form').reset();document.querySelector('#client-dialog').showModal()}
document.querySelector('#new-client').onclick=newClient;document.querySelector('#new-client-2').onclick=newClient;document.querySelector('#mobile-add').onclick=()=>selected==='all'&&!db.clients.length?newClient():openAsset();
document.querySelector('#client-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const name=String(f.get('name')).trim();if(!name)return;const c={id:crypto.randomUUID(),name,ref:String(f.get('ref')||'').trim(),assets:[]};db.clients.push(c);selected=c.id;save();e.currentTarget.closest('dialog').close();render();toast('Carteira criada para '+name)});
function openAsset(clientId=selected==='all'?db.clients[0]?.id:selected,symbol=''){if(!db.clients.length){newClient();return}if(selected==='all'&&!clientId){toast('Selecione um cliente');return}const c=db.clients.find(x=>x.id===clientId);if(!c)return;const existing=c.assets.find(a=>a.symbol===symbol);const form=document.querySelector('#asset-form');form.reset();form.dataset.client=c.id;form.dataset.symbol=existing?.symbol||'';form.querySelector('[name=symbol]').value=existing?.symbol||'';form.querySelector('[name=quantity]').value=existing?.quantity||'';form.querySelector('[name=cost]').value=existing?.cost||'';document.querySelector('#asset-title').textContent=existing?'Editar posição · '+c.name:'Nova posição · '+c.name;document.querySelector('#asset-dialog').showModal()}
document.querySelectorAll('[data-close-asset]').forEach(button=>button.addEventListener('click',()=>document.querySelector('#asset-dialog').close()));
document.querySelector('#asset-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const f=new FormData(form),client=db.clients.find(c=>c.id===form.dataset.client);if(!client)return;const symbol=String(f.get('symbol')).trim().toUpperCase().replace(/\.SA$/,'');const quantity=Number(f.get('quantity')),cost=Number(f.get('cost'));if(!symbol||quantity<=0||cost<=0){toast('Confira os dados informados');return}const ix=client.assets.findIndex(a=>a.symbol===form.dataset.symbol);const old=ix>=0?client.assets[ix]:null;const item={symbol,quantity,cost,price:old?.price||null,name:old?.name||symbol};if(ix>=0)client.assets[ix]=item;else client.assets.push(item);save();form.closest('dialog').close();render();toast('Posição salva')});
document.querySelector('#privacy-btn').onclick=()=>document.querySelector('#privacy-dialog').showModal();document.querySelector('#export-btn').onclick=exportBackup;
function exportBackup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='carteira-clara-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exportado')}
let quoteSyncRunning=false,lastQuoteSync=0;
async function refreshQuotes(silent=false){if(quoteSyncRunning)return;quoteSyncRunning=true;const buttons=[document.querySelector('#refresh-btn'),document.querySelector('#refresh-btn-page')];buttons.forEach(b=>{if(b)b.disabled=true});try{const response=await fetch('./data/quotes.json',{cache:'no-store'});if(!response.ok)throw new Error('O feed automático ainda não está disponível.');const feed=await response.json();if(!feed||!feed.quotes)throw new Error('O feed de cotações está vazio ou inválido.');let updated=0;for(const client of db.clients){for(const asset of client.assets||[]){const quote=feed.quotes[asset.symbol];if(!quote||!Number.isFinite(Number(quote.price)))continue;if(asset.quoteDate&&quote.date<asset.quoteDate)continue;asset.price=Number(quote.price);asset.quoteDate=quote.date;asset.quoteSource='COTAHIST';updated++}}if(feed.sourceDate&&(!db.quoteDate||feed.sourceDate>db.quoteDate))db.quoteDate=feed.sourceDate;db.quoteFeedUpdatedAt=feed.generatedAt||db.quoteFeedUpdatedAt;db.quoteSource='COTAHIST';db.updatedAt=feed.generatedAt||new Date().toISOString();save();render();lastQuoteSync=Date.now();document.querySelector('#quote-status').textContent=feed.sourceDate?`Último fechamento da B3: ${formatQuoteDate(feed.sourceDate)}.`:'Aguardando o primeiro arquivo COTAHIST diário.';if(!silent)toast(updated?`${updated} posição(ões) sincronizada(s) com os fechamentos da B3.`:'Feed consultado; sem preços novos para as posições cadastradas.')}catch(err){document.querySelector('#quote-status').textContent=db.quoteDate?`Sem conexão com o feed. Mantendo fechamentos de ${formatQuoteDate(db.quoteDate)}.`:'Automação ainda não publicada; a carteira segue disponível.';if(!silent)toast(err.message||'Não foi possível buscar os fechamentos da B3.')}finally{quoteSyncRunning=false;buttons.forEach(b=>{if(b)b.disabled=false})}}
document.querySelector('#refresh-btn').onclick=()=>refreshQuotes(false);document.querySelector('#refresh-btn-page').onclick=()=>refreshQuotes(false);
render();
refreshQuotes(true);setInterval(()=>refreshQuotes(true),6*60*60*1000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-lastQuoteSync>6*60*60*1000)refreshQuotes(true)});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
