const KEY='carteira-clara-v1';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const number=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:4});
let db=load(), selected='all', page='portfolio';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{clients:[]}}catch{return{clients:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function safe(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2700)}
function total(c){return(c.assets||[]).reduce((a,x)=>a+x.quantity*(x.price||x.cost),0)}
function invested(c){return(c.assets||[]).reduce((a,x)=>a+x.quantity*x.cost,0)}
function recordClientSnapshots(date){if(!date)return false;let changed=false;for(const client of db.clients){const history=Array.isArray(client.history)?client.history:[];if(!(client.assets||[]).length&&!history.length)continue;const point={date,value:total(client),invested:invested(client)},index=history.findIndex(item=>item.date===date);if(index>=0){if(history[index].value!==point.value||history[index].invested!==point.invested){history[index]=point;changed=true}}else{history.push(point);changed=true}history.sort((a,b)=>a.date.localeCompare(b.date));client.history=history.slice(-400)}return changed}
function fmt(v){return money.format(v||0)}
function formatQuoteDate(value){const digits=String(value||'').replace(/\D/g,'');return digits.length===8?`${digits.slice(6,8)}/${digits.slice(4,6)}/${digits.slice(0,4)}`:'data indisponível'}
function chartMoney(value){return value>=1000000?`R$ ${(value/1000000).toLocaleString('pt-BR',{maximumFractionDigits:1})} mi`:value>=1000?`R$ ${(value/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})} mil`:`R$ ${Math.round(value).toLocaleString('pt-BR')}`}
function historyPanel(clients){clients=clients.filter(client=>(client.assets||[]).length||(client.history||[]).length);const histories=clients.map(client=>new Map((client.history||[]).map(point=>[point.date,point])));const dates=histories.length?Array.from(histories[0].keys()).filter(date=>histories.every(history=>history.has(date))).sort():[];const points=dates.map(date=>({date,value:histories.reduce((sum,history)=>sum+history.get(date).value,0),invested:histories.reduce((sum,history)=>sum+history.get(date).invested,0)}));let graphic='';if(points.length){const w=720,h=220,left=78,right=14,top=14,bottom=34,plotW=w-left-right,plotH=h-top-bottom,max=Math.max(1,...points.flatMap(point=>[point.value,point.invested]))*1.08,x=i=>points.length===1?left+plotW/2:left+i*plotW/(points.length-1),y=value=>top+plotH-(value/max)*plotH,market=points.map((point,i)=>`${x(i)},${y(point.value)}`).join(' '),cost=points.map((point,i)=>`${x(i)},${y(point.invested)}`).join(' '),grid=[0,.5,1].map(ratio=>{const value=max*ratio,yy=y(value);return `<line class="chart-grid" x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}"/><text class="chart-axis" x="${left-9}" y="${yy+4}" text-anchor="end">${chartMoney(value)}</text>`}).join(''),labelIndexes=[...new Set([0,Math.floor((points.length-1)/2),points.length-1])],labels=labelIndexes.map(i=>`<text class="chart-axis" x="${x(i)}" y="${h-8}" text-anchor="middle">${formatQuoteDate(points[i].date).slice(0,5)}</text>`).join(''),dot=points.length===1?`<circle class="chart-market-dot" cx="${x(0)}" cy="${y(points[0].value)}" r="5"/>`:'';graphic=`<svg class="history-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Gráfico da evolução do valor de mercado e do custo investido">${grid}<polyline class="chart-invested" points="${cost}"/><polyline class="chart-market" points="${market}"/>${dot}${labels}</svg>`}const hint=points.length>1?`${formatQuoteDate(points[0].date)} a ${formatQuoteDate(points.at(-1).date)} · ${points.length} pregões registrados.`:points.length===1?`Primeiro ponto registrado em ${formatQuoteDate(points[0].date)}. O gráfico ganha uma linha após o próximo fechamento disponível.`:'O gráfico começará no primeiro fechamento da B3 registrado neste dispositivo.';return `<section class="panel history-panel"><div class="panel-heading"><div><h2>Evolução da carteira</h2><p>${selected==='all'?'Valor consolidado dos clientes selecionados':'Patrimônio e custo investido desta carteira'}</p></div></div>${graphic||'<div class="history-empty">Aguardando o primeiro fechamento disponível</div>'}<div class="chart-legend"><span><i class="legend-market"></i>Valor de mercado</span><span><i class="legend-invested"></i>Custo investido</span></div><p class="history-note">${hint} O histórico começa agora, sem reconstrução de períodos anteriores. Um ponto é salvo por data de fechamento quando o app consulta as cotações; se o app ficar fechado em um pregão, essa data poderá não entrar no gráfico.</p></section>`}
const assetCategories=['Ações e BDRs','Fundos imobiliários','ETFs','Renda fixa','Fundos','Outros','Não classificado'];
const categoryColors=['#146b52','#6f9f85','#dfa45f','#6e87bd','#a17ab1','#a8b3ad','#c1c9c4'];
function categoryName(asset){return assetCategories.includes(asset.category)?asset.category:'Não classificado'}
function allocationPanel(assets){if(!assets.length)return '';const groups=new Map();for(const asset of assets){const key=categoryName(asset);groups.set(key,(groups.get(key)||0)+asset.quantity*(asset.price||asset.cost))}const totalValue=[...groups.values()].reduce((sum,value)=>sum+value,0);if(!totalValue)return '';let cursor=0;const stops=[...groups].map(([name,value])=>{const start=cursor;cursor+=value/totalValue*100;return `${categoryColors[assetCategories.indexOf(name)]} ${start.toFixed(2)}% ${cursor.toFixed(2)}%`}).join(', ');const legend=[...groups].sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="allocation-item"><i style="--allocation-color:${categoryColors[assetCategories.indexOf(name)]}"></i><span>${safe(name)}</span><b>${(value/totalValue*100).toLocaleString('pt-BR',{maximumFractionDigits:1})}%</b><small>${fmt(value)}</small></div>`).join('');return `<section class="panel allocation-panel"><div class="panel-heading"><div><h2>Distribuição por classe</h2><p>Composição pelo valor de mercado estimado</p></div></div><div class="allocation"><div class="allocation-donut" role="img" aria-label="Distribuição da carteira por classe" style="--allocation-stops:${stops}"><span>${fmt(totalValue)}</span></div><div class="allocation-legend">${legend}</div></div></section>`}
function dateText(){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'long',year:'numeric'}).format(new Date())}
document.querySelector('#today').textContent=dateText();
function render(){
  document.querySelector('#client-strip').innerHTML=`<button class="client-tab all ${selected==='all'?'active':''}" data-client="all">Todos os clientes</button>`+db.clients.map(c=>`<button class="client-tab ${selected===c.id?'active':''}" data-client="${c.id}">${safe(c.name)}</button>`).join('');
  document.querySelectorAll('[data-client]').forEach(b=>b.onclick=()=>{selected=b.dataset.client;render()});
  renderPortfolio();renderClients();
}
function renderPortfolio(){
 const clients=selected==='all'?db.clients:db.clients.filter(c=>c.id===selected);const assets=clients.flatMap(c=>(c.assets||[]).map(a=>({...a,clientName:c.name,clientId:c.id})));const mv=clients.reduce((n,c)=>n+total(c),0),cost=clients.reduce((n,c)=>n+invested(c),0),pnl=mv-cost, pct=cost?pnl/cost*100:0;
 document.querySelector('#crumb-client').textContent=selected==='all'?'Visão geral':(clients[0]?.name||'Visão geral');document.querySelector('#portfolio-title').textContent=selected==='all'?'Suas carteiras':'Carteira de '+(clients[0]?.name||'cliente');document.querySelector('#portfolio-page .subheading').textContent=selected==='all'?'Visão consolidada dos investimentos dos seus clientes.':'Acompanhamento da carteira de '+(clients[0]?.name||'cliente')+'.';document.querySelector('#portfolio-print-meta').textContent='Relatório gerado em '+dateText()+' · '+(selected==='all'?'Todos os clientes':clients[0]?.name||'Carteira');
 const content=document.querySelector('#portfolio-content');
 if(!db.clients.length){content.innerHTML=`<div class="empty"><div class="empty-icon">♙</div><h2>Comece pelo primeiro cliente</h2><p>Crie uma carteira separada para cada cliente e acompanhe os investimentos em um só lugar.</p><button class="primary" id="empty-new">＋ Cadastrar primeiro cliente</button></div>`;document.querySelector('#empty-new').onclick=()=>document.querySelector('#client-dialog').showModal();return}
 const head=`<div class="stats"><div class="stat-card"><div class="stat-label">Patrimônio de mercado</div><div class="stat-value">${fmt(mv)}</div><div class="stat-foot">${selected==='all'?`${db.clients.length} clientes`:'Carteira de '+safe(clients[0]?.name)}</div></div><div class="stat-card"><div class="stat-label">Total investido</div><div class="stat-value">${fmt(cost)}</div><div class="stat-foot">Custo médio informado</div></div><div class="stat-card"><div class="stat-label">Resultado acumulado</div><div class="stat-value ${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}${fmt(pnl)}</div><div class="stat-foot ${pnl>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2).replace('.',',')}% sobre o custo</div></div><div class="stat-card"><div class="stat-label">Ativos na carteira</div><div class="stat-value">${assets.length}</div><div class="stat-foot">${new Set(assets.map(a=>a.symbol)).size} códigos distintos</div></div></div>`;
 const rows=assets.map(a=>{const gain=a.quantity*((a.price||a.cost)-a.cost),gpct=a.cost?((a.price||a.cost)-a.cost)/a.cost*100:0;return `<tr data-search="${safe((a.symbol+' '+a.clientName+' '+categoryName(a)).toLocaleLowerCase())}"><td><div class="asset-symbol">${safe(a.symbol)}</div><div class="asset-name">${selected==='all'?safe(a.clientName):safe(a.name||'Ativo')}</div></td><td>${safe(categoryName(a))}</td><td>${number.format(a.quantity)}</td><td>${fmt(a.cost)}</td><td>${a.price?`${fmt(a.price)}<div class="asset-name">${formatQuoteDate(a.quoteDate||db.quoteDate)}</div>${a.quoteDate&&db.quoteDate&&a.quoteDate<db.quoteDate?'<span class="quote-stale">Preço antigo</span>':''}`:'<span class="stat-foot">Sem cotação</span>'}</td><td>${fmt(a.quantity*(a.price||a.cost))}</td><td class="${gain>=0?'positive':'negative'}">${gain>=0?'+':''}${fmt(gain)}<div class="asset-name ${gain>=0?'positive':'negative'}">${gpct>=0?'+':''}${gpct.toFixed(2).replace('.',',')}%</div></td><td class="position-actions"><button class="subtle-btn edit-asset" data-client="${a.clientId}" data-symbol="${safe(a.symbol)}" title="Editar posição" aria-label="Editar ${safe(a.symbol)}">✎</button><button class="subtle-btn delete-asset" data-client="${a.clientId}" data-symbol="${safe(a.symbol)}" title="Excluir posição" aria-label="Excluir ${safe(a.symbol)}">×</button></td></tr>`}).join('');
 content.innerHTML=head+allocationPanel(assets)+historyPanel(clients)+(assets.length?`<div class="panel"><div class="panel-heading"><div><h2>Posições</h2><p>${selected==='all'?'Consolidado de todos os clientes':'Ativos desta carteira'}</p></div><button class="primary" id="add-asset">＋ Ativo</button></div><div class="table-tools"><input id="position-search" type="search" placeholder="Buscar ticker ou cliente" aria-label="Buscar posição"><select id="category-filter" aria-label="Filtrar por classe"><option value="">Todas as classes</option>${assetCategories.map(category=>`<option>${safe(category)}</option>`).join('')}</select><span id="position-count"></span></div><div class="table-wrap"><table><thead><tr><th>Ativo / cliente</th><th>Classe</th><th>Quantidade</th><th>Custo médio</th><th>Cotação</th><th>Valor atual</th><th>Rentabilidade</th><th></th></tr></thead><tbody>${rows}</tbody></table></div><div class="note">${db.quoteDate?'Último pregão disponível: '+db.quoteDate.slice(6,8)+'/'+db.quoteDate.slice(4,6)+'/'+db.quoteDate.slice(0,4)+'. ':''}${db.updatedAt?'Preços sincronizados em '+new Date(db.updatedAt).toLocaleString('pt-BR')+'. ':''}A rentabilidade considera apenas variação de preço e custo médio cadastrado.</div></div>`:`<div class="empty"><div class="empty-icon">↗</div><h2>${selected==='all'?'Adicione o primeiro investimento':'Esta carteira ainda está vazia'}</h2><p>Registre quantidade e custo médio. O valor de mercado será calculado com a cotação disponível ou com o custo informado.</p><button class="primary" id="add-asset-empty">＋ Adicionar ativo</button></div>`);
 const searchInput=content.querySelector('#position-search'),categoryFilter=content.querySelector('#category-filter'),positionCount=content.querySelector('#position-count');function filterPositions(){const term=(searchInput?.value||'').trim().toLocaleLowerCase(),category=categoryFilter?.value||'';let visible=0;content.querySelectorAll('tbody tr').forEach(row=>{const matches=(!term||row.dataset.search.includes(term))&&(!category||row.children[1]?.textContent===category);row.hidden=!matches;if(matches)visible++});if(positionCount)positionCount.textContent=`${visible} ${visible===1?'posição':'posições'}`}searchInput?.addEventListener('input',filterPositions);categoryFilter?.addEventListener('change',filterPositions);filterPositions();const add=document.querySelector('#add-asset')||document.querySelector('#add-asset-empty');if(add)add.onclick=()=>openAsset();document.querySelectorAll('.edit-asset').forEach(b=>b.onclick=()=>openAsset(b.dataset.client,b.dataset.symbol));document.querySelectorAll('.delete-asset').forEach(b=>b.onclick=()=>deleteAsset(b.dataset.client,b.dataset.symbol));
}
function deleteAsset(clientId,symbol){const client=db.clients.find(c=>c.id===clientId);const asset=client?.assets.find(a=>a.symbol===symbol);if(!client||!asset)return;if(!window.confirm(`Excluir ${asset.symbol} da carteira de ${client.name}?`))return;client.assets=client.assets.filter(a=>a.symbol!==symbol);recordClientSnapshots(db.quoteDate);save();render();toast(`${asset.symbol} removido da carteira`)}
function deleteClient(clientId){const client=db.clients.find(c=>c.id===clientId);if(!client)return;const positionCount=(client.assets||[]).length;const detail=positionCount?" e suas "+positionCount+" "+(positionCount===1?"posição":"posições"): "";if(!window.confirm("Excluir o cliente "+client.name+detail+"? A carteira e o histórico desse cliente serão removidos permanentemente deste dispositivo."))return;db.clients=db.clients.filter(c=>c.id!==clientId);if(selected===clientId)selected="all";save();render();toast("Cliente "+client.name+" excluído")}function renderClients(){const el=document.querySelector('#clients-content');if(!db.clients.length){el.innerHTML='<div class="empty"><div class="empty-icon">♙</div><h2>Nenhum cliente cadastrado</h2><p>Adicione um cliente para criar a primeira carteira.</p><button class="primary" id="client-empty-add">＋ Novo cliente</button></div>';document.querySelector('#client-empty-add').onclick=()=>document.querySelector('#client-dialog').showModal();return}el.innerHTML='<div class="client-list">'+db.clients.map(c=>`<div class="client-row"><div class="client-initial">${safe(c.name[0].toUpperCase())}</div><div class="client-info"><b>${safe(c.name)}</b><small>${safe(c.ref||'Carteira de investimentos')} · ${(c.assets||[]).length} ativos</small></div><div class="client-value">${fmt(total(c))}<small>patrimônio estimado</small></div><div class="client-actions"><button class="secondary open-client" data-id="${c.id}">Abrir carteira</button><button class="secondary delete-client" data-id="${c.id}" aria-label="Excluir cliente ${safe(c.name)}" title="Excluir cliente">Excluir</button></div></div>`).join('')+'</div>';document.querySelectorAll('.open-client').forEach(b=>b.onclick=()=>{selected=b.dataset.id;showPage('portfolio')});document.querySelectorAll('.delete-client').forEach(b=>b.onclick=()=>deleteClient(b.dataset.id))}
function showPage(p){page=p;document.querySelector('#portfolio-page').classList.toggle('hidden',p!=='portfolio');document.querySelector('#clients-page').classList.toggle('hidden',p!=='clients');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function newClient(){document.querySelector('#client-form').reset();document.querySelector('#client-dialog').showModal()}
document.querySelector('#new-client').onclick=newClient;document.querySelectorAll('[data-close-client]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog')?.close()));document.querySelector('#new-client-2').onclick=newClient;document.querySelector('#mobile-add').onclick=()=>selected==='all'&&!db.clients.length?newClient():openAsset();
document.querySelector('#client-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(e.submitter?.value==='cancel'){form.closest('dialog').close();return}const input=form.elements.namedItem('name');input.setCustomValidity('');if(!input.value.trim()){input.setCustomValidity('Informe o nome do cliente para criar a carteira.');input.reportValidity();input.setCustomValidity('');return}if(!form.reportValidity())return;const f=new FormData(form);const name=String(f.get('name')).trim();const c={id:crypto.randomUUID(),name,ref:String(f.get('ref')||'').trim(),assets:[]};db.clients.push(c);selected=c.id;save();e.currentTarget.closest('dialog').close();render();toast('Carteira criada para '+name)});
function openAsset(clientId=selected==='all'?db.clients[0]?.id:selected,symbol=''){if(!db.clients.length){newClient();return}if(selected==='all'&&!clientId){toast('Selecione um cliente');return}const c=db.clients.find(x=>x.id===clientId);if(!c)return;const existing=c.assets.find(a=>a.symbol===symbol);const form=document.querySelector('#asset-form');form.reset();form.dataset.client=c.id;form.dataset.symbol=existing?.symbol||'';form.querySelector('[name=symbol]').value=existing?.symbol||'';form.querySelector('[name=quantity]').value=existing?.quantity||'';form.querySelector('[name=cost]').value=existing?.cost||'';form.querySelector('[name=category]').value=categoryName(existing||{});document.querySelector('#asset-title').textContent=existing?'Editar posição · '+c.name:'Nova posição · '+c.name;document.querySelector('#asset-dialog').showModal()}
document.querySelectorAll('[data-close-asset]').forEach(button=>button.addEventListener('click',()=>document.querySelector('#asset-dialog').close()));
document.querySelector('#asset-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const f=new FormData(form),client=db.clients.find(c=>c.id===form.dataset.client);if(!client)return;const symbol=String(f.get('symbol')).trim().toUpperCase().replace(/\.SA$/,'');const quantity=Number(f.get('quantity')),cost=Number(f.get('cost'));if(!symbol||quantity<=0||cost<=0){toast('Confira os dados informados');return}const ix=client.assets.findIndex(a=>a.symbol===form.dataset.symbol);const old=ix>=0?client.assets[ix]:null;const item={symbol,quantity,cost,category:assetCategories.includes(f.get('category'))?f.get('category'):'Ações e BDRs',price:old?.price||null,name:old?.name||symbol};if(ix>=0)client.assets[ix]=item;else client.assets.push(item);recordClientSnapshots(db.quoteDate);save();form.closest('dialog').close();render();toast('Posição salva')});
document.querySelector('#privacy-btn').onclick=()=>document.querySelector('#privacy-dialog').showModal();document.querySelector('#export-btn').onclick=exportBackup;document.querySelector('#print-report').onclick=()=>window.print();
function exportBackup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='carteira-clara-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exportado')}
function restoreBackup(file){const reader=new FileReader();reader.onload=()=>{try{const backup=JSON.parse(String(reader.result||''));if(!backup||!Array.isArray(backup.clients))throw new Error('O arquivo não parece ser um backup Carteira Clara.');if(!window.confirm('Restaurar este backup substituirá as carteiras salvas neste navegador. Deseja continuar?'))return;const clients=backup.clients.map(client=>{const name=String(client.name||'').trim().slice(0,60);if(!name)throw new Error('Há um cliente sem nome válido no arquivo.');const assets=(Array.isArray(client.assets)?client.assets:[]).map(asset=>{const symbol=String(asset.symbol||'').trim().toUpperCase();const quantity=Number(asset.quantity),cost=Number(asset.cost);if(!/^[A-Z0-9._^-]{1,15}$/.test(symbol)||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(cost)||cost<=0)throw new Error('O arquivo contém uma posição inválida.');return{symbol,quantity,cost,category:assetCategories.includes(asset.category)?asset.category:'Ações e BDRs',price:Number.isFinite(Number(asset.price))&&Number(asset.price)>0?Number(asset.price):null,name:String(asset.name||symbol).slice(0,60),quoteDate:/^\d{8}$/.test(String(asset.quoteDate||''))?String(asset.quoteDate):null,quoteSource:String(asset.quoteSource||'').slice(0,30)}});const history=(Array.isArray(client.history)?client.history:[]).filter(point=>/^\d{8}$/.test(String(point.date||''))&&Number.isFinite(Number(point.value))&&Number.isFinite(Number(point.invested))).map(point=>({date:String(point.date),value:Number(point.value),invested:Number(point.invested)})).slice(-400);return{id:crypto.randomUUID(),name,ref:String(client.ref||'').slice(0,30),assets,history}});db={...backup,clients};selected='all';save();render();document.querySelector('#privacy-dialog').close();toast('Backup restaurado')}catch(error){toast(error.message||'Não foi possível restaurar este backup')}finally{document.querySelector('#import-backup').value=''}};reader.readAsText(file)}
document.querySelector('#import-backup').addEventListener('change',event=>{const file=event.currentTarget.files?.[0];if(file)restoreBackup(file)})
let quoteSyncRunning=false,lastQuoteSync=0;
async function refreshQuotes(silent=false){if(quoteSyncRunning)return;quoteSyncRunning=true;const buttons=[document.querySelector('#refresh-btn'),document.querySelector('#refresh-btn-page')];buttons.forEach(b=>{if(b)b.disabled=true});try{const response=await fetch('./data/quotes.json',{cache:'no-store'});if(!response.ok)throw new Error('O feed automático ainda não está disponível.');const feed=await response.json();if(!feed||!feed.quotes)throw new Error('O feed de cotações está vazio ou inválido.');let updated=0;for(const client of db.clients){for(const asset of client.assets||[]){const quote=feed.quotes[asset.symbol];if(!quote||!Number.isFinite(Number(quote.price)))continue;if(asset.quoteDate&&quote.date<asset.quoteDate)continue;asset.price=Number(quote.price);asset.quoteDate=quote.date;asset.quoteSource='COTAHIST';updated++}}const previousDate=db.quoteDate;if(feed.sourceDate&&(!previousDate||feed.sourceDate>=previousDate)){db.quoteDate=feed.sourceDate;recordClientSnapshots(feed.sourceDate)}db.quoteFeedUpdatedAt=feed.generatedAt||db.quoteFeedUpdatedAt;db.quoteSource='COTAHIST';db.updatedAt=feed.generatedAt||new Date().toISOString();save();render();lastQuoteSync=Date.now();document.querySelector('#quote-status').textContent=feed.sourceDate?`Último fechamento da B3: ${formatQuoteDate(feed.sourceDate)}.`:'Aguardando o primeiro arquivo COTAHIST diário.';if(!silent)toast(updated?`${updated} posição(ões) sincronizada(s) com os fechamentos da B3.`:'Feed consultado; sem preços novos para as posições cadastradas.')}catch(err){document.querySelector('#quote-status').textContent=db.quoteDate?`Sem conexão com o feed. Mantendo fechamentos de ${formatQuoteDate(db.quoteDate)}.`:'Automação ainda não publicada; a carteira segue disponível.';if(!silent)toast(err.message||'Não foi possível buscar os fechamentos da B3.')}finally{quoteSyncRunning=false;buttons.forEach(b=>{if(b)b.disabled=false})}}
document.querySelector('#refresh-btn').onclick=()=>refreshQuotes(false);document.querySelector('#refresh-btn-page').onclick=()=>refreshQuotes(false);
render();
refreshQuotes(true);setInterval(()=>refreshQuotes(true),6*60*60*1000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-lastQuoteSync>6*60*60*1000)refreshQuotes(true)});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
