(()=>{
const KEY='carteira-clara-opportunities-v1',fmt=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),percent=v=>(v*100).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
let plans=[];try{plans=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}
const page=document.createElement('section');page.id='opportunities-page';page.className='page hidden';page.innerHTML='<div class="page-heading"><div><p class="eyebrow">ANÁLISE PESSOAL</p><h1>Oportunidades</h1><p class="subheading">Registre suas ideias e compare cenários de retorno e risco.</p></div></div><div class="opp-notice"><b>Ferramenta de análise, não recomendação.</b> Defina sua própria tese, preço-alvo e limite de perda. O feed disponível traz apenas o último fechamento da B3; os cenários são estimativas suas e podem não se concretizar.</div><section class="panel opp-form-panel"><div class="panel-heading"><div><h2>Novo cenário</h2><p>Os preços-alvo e limites são definidos por você.</p></div></div><form id="opp-form" class="opp-form"><label>Ticker<input name="symbol" required maxlength="8" placeholder="Ex.: PETR4" autocomplete="off"></label><label>Estratégia<select name="strategy"><option>Acompanhamento</option><option>Tendência</option><option>Valor</option><option>Dividendos</option><option>Outra</option></select></label><label>Preço-alvo (R$)<input name="target" type="number" min="0.01" step="0.01" required></label><label>Limite de perda (R$)<input name="stop" type="number" min="0.01" step="0.01" required></label><label class="opp-thesis">Tese e riscos<textarea name="thesis" rows="2" maxlength="240" placeholder="Por que está acompanhando? O que invalidaria a tese?" required></textarea></label><button class="primary" type="submit">＋ Salvar cenário</button></form></section><section class="panel"><div class="panel-heading"><div><h2>Meus cenários</h2><p>Relação retorno/risco calculada sobre o último fechamento.</p></div></div><p class="opp-feed" id="opp-feed">Carregando fechamentos da B3…</p><div id="opp-list"></div><p class="note">A relação retorno/risco compara o ganho potencial até o alvo definido por você com a perda potencial até seu limite. Não considera custos, impostos, liquidez ou gaps de preço; não é uma indicação de compra ou venda.</p></section>';
document.querySelector('main.main').insertBefore(page,document.querySelector('footer.disclaimer'));
const style=document.createElement('style');style.textContent='.opp-notice{background:#fff8e9;border:1px solid #f1d49b;border-radius:14px;padding:16px 18px;margin:18px 0;color:#684d18;line-height:1.55}.opp-form{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:14px;align-items:end}.opp-form label{display:grid;gap:7px;font-size:13px;color:#526158}.opp-form input,.opp-form select,.opp-form textarea{box-sizing:border-box;width:100%;padding:11px;border:1px solid #dce4de;border-radius:9px;font:inherit;color:#20352b;background:white}.opp-form textarea{resize:vertical}.opp-thesis{grid-column:span 3}.opp-list{display:grid;gap:12px}.opp-row{display:grid;grid-template-columns:1fr 1fr 1fr 1fr 1.3fr auto;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid #edf0ed}.opp-row small{display:block;color:#748078;margin-top:4px}.opp-remove{border:0;background:transparent;color:#8b5148;cursor:pointer;padding:8px}.opp-empty{padding:20px;color:#65736a}.opp-feed{font-size:13px;color:#68766d;margin:0 0 12px}@media(max-width:760px){.opp-form{grid-template-columns:1fr 1fr}.opp-thesis{grid-column:span 2}.opp-row{grid-template-columns:1fr 1fr}.opp-row>button{justify-self:start}}';document.head.appendChild(style);
const side=document.querySelector('.sidebar .nav-item[data-page="clients"]');const desk=document.createElement('button');desk.className='nav-item';desk.dataset.page='opportunities';desk.textContent='⌖  Oportunidades';side.after(desk);const mobile=document.createElement('button');mobile.dataset.page='opportunities';mobile.innerHTML='⌖<small>Radar</small>';document.querySelector('.mobile-nav').insertBefore(mobile,document.querySelector('#mobile-add'));
function openPage(){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('hidden',p.id!=='opportunities-page'));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='opportunities'));render()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b&&b.dataset.page==='opportunities'){e.preventDefault();e.stopImmediatePropagation();openPage()}else if(b&&b.dataset.page!=='opportunities')page.classList.add('hidden')},true);
function quoteDate(d){return d&&d.length===8?d.slice(6,8)+'/'+d.slice(4,6)+'/'+d.slice(0,4):'sem data'}
function render(){const host=document.querySelector('#opp-list');host.className='opp-list';if(!plans.length){host.innerHTML='<div class="opp-empty">Nenhum cenário cadastrado. Comece registrando uma tese que queira acompanhar.</div>';return}host.innerHTML=plans.map((p,i)=>{const q=window.oppQuotes?.[p.symbol],price=Number(q?.price),up=price>0?(Number(p.target)-price)/price:null,down=price>0?(price-Number(p.stop))/price:null,rr=up>0&&down>0?up/down:null;return '<article class="opp-row"><div><b>'+escapeHTML(p.symbol)+'</b><small>'+escapeHTML(p.strategy)+'</small></div><div>'+(price>0?fmt.format(price):'Sem cotação')+'<small>'+(q?quoteDate(q.date):'Confira o ticker')+'</small></div><div>'+fmt.format(Number(p.target))+'<small>alvo definido por você</small></div><div>'+fmt.format(Number(p.stop))+'<small>limite definido por você</small></div><div>'+(up!==null?percent(up)+' até o alvo':'—')+(rr!==null?' · '+rr.toFixed(1).replace('.',',')+':1 retorno/risco':'')+'<small>'+escapeHTML(p.thesis)+'</small></div><button class="opp-remove" data-remove="'+i+'" aria-label="Excluir cenário '+escapeHTML(p.symbol)+'">Excluir</button></article>'}).join('');host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{plans.splice(Number(b.dataset.remove),1);persist()})}
function persist(){localStorage.setItem(KEY,JSON.stringify(plans));render()}
document.querySelector('#opp-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),symbol=String(f.get('symbol')).trim().toUpperCase().replace(/\.SA$/,'');const target=Number(f.get('target')),stop=Number(f.get('stop'));if(!/^[A-Z0-9]{4,6}$/.test(symbol)){alert('Informe um ticker válido, como PETR4.');return}if(!(target>stop)){alert('O preço-alvo deve ser maior que o limite de perda.');return}plans.unshift({symbol,strategy:f.get('strategy'),target,stop,thesis:String(f.get('thesis')).trim()});e.currentTarget.reset();persist()});
window.oppQuotes={};fetch('./data/quotes.json',{cache:'no-store'}).then(r=>r.json()).then(feed=>{window.oppQuotes=feed.quotes||{};document.querySelector('#opp-feed').textContent='Fechamento B3: '+quoteDate(feed.sourceDate)+' · '+Object.keys(window.oppQuotes).length+' ativos no feed.';render()}).catch(()=>{document.querySelector('#opp-feed').textContent='Não foi possível carregar o feed. Seus cenários continuam salvos neste dispositivo.';render()});
})();
